# Numpy:-

### 1.> It is a array-matrix module which develope by travis oliphant in c++.

### 2.> It deals with unstructed data.

### 3.> In python it come with warper which convert the code into c++.

### 4.> In pandas , internally numpy is working.

### 5.> Numpy is used to create (1d,2d,3d...)array.

### 6.> Array is a data type which store simple data into a container.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [16]:
np.zeros((10,10),dtype=np.int_)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.ones((10,10),dtype=np.int_)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [18]:
a=[1,2,3,4,5,6,7]

In [26]:
b=np.array(a)
print(b,'dimension:--->',b.ndim)

[1 2 3 4 5 6 7] dimension:---> 1


In [31]:
c=np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(c,'dimension:--->',c.ndim)

[[1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]] dimension:---> 2


In [35]:
np.full((4,5),10,dtype=np.int_)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [40]:
c=np.array([[1,2,3,4,5,6,7],[10,0,20,5,5,30,80]],order='F')
print(c,'dimension:--->',c.ndim)

[[ 1  2  3  4  5  6  7]
 [10  0 20  5  5 30 80]] dimension:---> 2


In [46]:
x=np.random.randint(10,100,(10,3),np.int_)
x

array([[52, 69, 55],
       [48, 25, 15],
       [32, 89, 93],
       [79, 76, 23],
       [62, 57, 94],
       [91, 61, 58],
       [73, 61, 32],
       [87, 37, 41],
       [92, 32, 99],
       [45, 79, 98]])

In [55]:
c=np.reshape(x,(15,2),order='c')
c

array([[52, 69],
       [55, 48],
       [25, 15],
       [32, 89],
       [93, 79],
       [76, 23],
       [62, 57],
       [94, 91],
       [61, 58],
       [73, 61],
       [32, 87],
       [37, 41],
       [92, 32],
       [99, 45],
       [79, 98]])

In [68]:
d=np.reshape(x,(15,2),order='f')
d

array([[52, 61],
       [48, 61],
       [32, 37],
       [79, 32],
       [62, 79],
       [91, 55],
       [73, 15],
       [87, 93],
       [92, 23],
       [45, 94],
       [69, 58],
       [25, 32],
       [89, 41],
       [76, 99],
       [57, 98]])

In [69]:
np.linspace(100,1000,10)

array([ 100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,  900.,
       1000.])

In [70]:
c

array([[52, 69],
       [55, 48],
       [25, 15],
       [32, 89],
       [93, 79],
       [76, 23],
       [62, 57],
       [94, 91],
       [61, 58],
       [73, 61],
       [32, 87],
       [37, 41],
       [92, 32],
       [99, 45],
       [79, 98]])

In [71]:
d

array([[52, 61],
       [48, 61],
       [32, 37],
       [79, 32],
       [62, 79],
       [91, 55],
       [73, 15],
       [87, 93],
       [92, 23],
       [45, 94],
       [69, 58],
       [25, 32],
       [89, 41],
       [76, 99],
       [57, 98]])

In [87]:
a=np.array([[2,0],[52,8]])
b=np.array([[20,0],[52,80]])
print(a)  

[[ 2  0]
 [52  8]]


In [88]:
b

array([[20,  0],
       [52, 80]])

In [89]:
a.dot(b)

array([[  40,    0],
       [1456,  640]])

In [92]:
np.hstack((a,b))


array([[ 2,  0, 20,  0],
       [52,  8, 52, 80]])

In [93]:
np.vstack((a,b))


array([[ 2,  0],
       [52,  8],
       [20,  0],
       [52, 80]])

In [94]:
a

array([[ 2,  0],
       [52,  8]])

In [97]:
a.transpose()

array([[ 2, 52],
       [ 0,  8]])

In [98]:
a.T

array([[ 2, 52],
       [ 0,  8]])